### ISSUE TITLE
karma tests fail

### ISSUE THREAD

**Issue by bengro** [cmlenz/tsify-test#1]
I would be interested in your browserify/tsify setup in order to run TypeScript specs in karma. I tried running the tests, but I get failures when doing so.

/node_modules/karma/bin/karma start, I get:

> ERROR [framework.browserify]: bundle error
> ERROR [framework.browserify]: TypeScript error: src/adder.spec.ts(7,21): Error TS2304: Cannot find name 'Adder'.
> WARN [karma]: Port 9876 in use
> INFO [karma]: Karma v0.12.37 server started at http://localhost:9877/
> INFO [launcher]: Starting browser PhantomJS
> INFO [framework.browserify]: 2366 bytes written (0.20 seconds)
> INFO [framework.browserify]: bundle updated
> INFO [watcher]: Changed file "/var/folders/x3/s5vqwx2s2cj5q331m6171vz00000gn/T/08c2c13a28ec5c3403a215e8f663652a.browserify".
> WARN [karma]: No captured browser, open http://localhost:9877/
> INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket L6Qca_q1P00Jy_2lZN7c with id 26214768
> PhantomJS 1.9.8 (Mac OS X 0.0.0) test adder should add FAILED
>   ReferenceError: Can't find variable: Adder
>       at /var/folders/x3/s5vqwx2s2cj5q331m6171vz00000gn/T/08c2c13a28ec5c3403a215e8f663652a.browserify:5:0 <- null:0:0
> PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.006 secs / 0.001 secs)

Running gulp test, I get:

> [23:02:07] Using gulpfile ~/workspace/tsify-test/gulpfile.js
> [23:02:07] Starting 'test'...
> ERROR [framework.browserify]: bundle error
> ERROR [framework.browserify]: TypeScript error: src/adder.spec.ts(7,21): Error TS2304: Cannot find name 'Adder'.
> WARN [karma]: Port 9876 in use
> INFO [karma]: Karma v0.12.37 server started at http://localhost:9877/
> INFO [launcher]: Starting browser PhantomJS
> INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket AxHrOyzYy9LWF4RRZR2O with id 3885825
> PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
>   TEST RUN WAS CANCELLED because this file contains some errors:
>     /var/folders/x3/s5vqwx2s2cj5q331m6171vz00000gn/T/9e29dd310d476864a6876823e6222d57.browserify

Before running the tests I ran npm install && gulp build.

I would be very interested in seeing this work!

**Comment by cmlenz** [comment]
The failure was actually intentional to check out how this setup deals with different types of errors. I've just updated the whole project, and added a note to the README on how to fix the test failures, so you can actually see it does work.

**Comment by bengro** [comment]
Sorry, should have realised. Thanks a lot for clarifying - it all works!
